INCLUDE_DIRECTORY=include
OBJECTS_DIRECTORY=objects
SOURCES_DIRECTORY=sources

TESTS_DIRECTORY=tests
TESTS_INCLUDE_DIRECTORY=$(TESTS_DIRECTORY)/include
TESTS_SOURCES_DIRECTORY=$(TESTS_DIRECTORY)/sources
TESTS_OBJECTS_DIRECTORY=$(TESTS_DIRECTORY)/objects

SOURCE_FILES=$(wildcard $(SOURCES_DIRECTORY)/*.c)
OBJECT_FILES=$(patsubst $(SOURCES_DIRECTORY)/%.c, $(OBJECTS_DIRECTORY)/%.o, $(SOURCE_FILES))

TESTS_SOURCE_FILES=$(wildcard $(TESTS_SOURCES_DIRECTORY)/*.c)
TESTS_OBJECT_FILES=$(patsubst $(TESTS_SOURCES_DIRECTORY)/%.c, $(TESTS_OBJECTS_DIRECTORY)/%.o, $(TESTS_SOURCE_FILES))

OUT_FILE=$(OBJECTS_DIRECTORY)/math.o

CC=gcc
C_FLAGS=-O3 -I$(INCLUDE_DIRECTORY)

LD=ld
LD_FLAGS=

$(OUT_FILE): $(OBJECT_FILES)
	$(LD) $(LD_FLAGS) -r $^ -o $@

$(OBJECTS_DIRECTORY)/%.o: $(SOURCES_DIRECTORY)/%.c
	$(CC) $(C_FLAGS) -c $< -o $@

tests: $(TESTS_OBJECT_FILES) $(OBJECT_FILES)
	$(CC) $(C_FLAGS) $^ -o $(TESTS_DIRECTORY)/tests

$(TESTS_OBJECTS_DIRECTORY)/%.o: $(TESTS_SOURCES_DIRECTORY)/%.c
	$(CC) $(C_FLAGS) -I$(TESTS_INCLUDE_DIRECTORY) -c $< -o $@

clean:
	-rm $(OBJECTS_DIRECTORY)/*.o $(TESTS_OBJECTS_DIRECTORY)/*.o 2> /dev/null

