name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: create directories
      run: mkdir -p objects tests/objects
    - name: make
      run: make
    - name: make tests
      run: make tests
    - name: tests
      run: ./tests/tests
